---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sources-volume-claim
  namespace: default
spec:
  storageClassName: slow
  volumeName: default-sources-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
